version: "3"
services:
  education-app:
#    build: .
    image: education-rest:1.0
    ports:
      - "8002:8002"
    networks:
      - education-2-db
    depends_on:
      - education-mysql-db
    container_name: education-app

  education-mysql-db:
    image: mysql
    networks:
      - education-2-db
    environment:
      - MYSQL_ROOT_PASSWORD=sudnxp5698884
      - MYSQL_DATABASE=education_db
    container_name: education-mysql-db

networks:
  education-2-db:

